### ISSUE TITLE
Can't get the test script to work correctly

### ISSUE THREAD

**Issue by clarkezone** [nlsandler/write_a_c_compiler#1]
cloned your repo onto my mac and copied my compiler binary into the root.  If i run the script from that directory i get this which is an error in the script:

new-host-5:write_a_c_compiler james$ ./test_compiler.sh ./simple_c_compiler
====================================================
STAGE 1
===================Valid Programs===================
./test_compiler.sh: line 28: ././stage_1/valid/multi_digit: No such file or directory
multi_digit..............FAIL
rm: ./stage_1/valid/multi_digit: No such file or directory
./test_compiler.sh: line 28: ././stage_1/valid/newlines: No such file or directory
newlines..............FAIL
rm: ./stage_1/valid/newlines: No such file or directory
./test_compiler.sh: line 28: ././stage_1/valid/no_newlines: No such file or directory
no_newlines..............FAIL
rm: ./stage_1/valid/no_newlines: No such file or directory
./test_compiler.sh: line 28: ././stage_1/valid/return_0: No such file or directory
return_0..............FAIL
rm: ./stage_1/valid/return_0: No such file or directory
./test_compiler.sh: line 28: ././stage_1/valid/return_2: No such file or directory
return_2..............FAIL
rm: ./stage_1/valid/return_2: No such file or directory
./test_compiler.sh: line 28: ././stage_1/valid/spaces: No such file or directory
spaces..............FAIL
rm: ./stage_1/valid/spaces: No such file or directory
===================Invalid Programs=================
missing_paren..............OK
missing_retval..............OK
no_brace..............OK
no_semicolon..............OK
no_space..............OK
wrong_case..............OK
===================Stage 1 Summary=================
6 successes, 6 failures

If i invoke my compiler manually i get this indicating it is working.  Looks like a bug in the script?:

new-host-5:write_a_c_compiler james$ ./simple_c_compiler ./stage_1/valid/multi_digit.c 
Found function name:main
Found number:100
CODEGEN: Expression
CODEGEN: Statement
CODEGEN: Function
CODEGEN: Program
EMMIT:.globl main
EMMIT:main:
EMMIT:mov $100, %eax
EMMIT:ret
Writing .globl main
Writing main:
Writing mov $100, %eax
Writing ret

**Comment by nlsandler** [comment]
Thanks for reporting this! At first glance, it looks like the problem here is that your compiler isn't writing executables where the test script expects them. When you run: 
`$ ./simple_c_compiler ./stage_1/valid/multi_digit.c`
it should save the binary executable at `./stage_1/valid/multi_digit` in order for the test script to work.

Any chance that's the issue?

**Comment by clarkezone** [comment]
Bingo.  That was it, thx.  Your instructions were clear, i just didn't read them carefully enough.  Only one failing stage one test now: https://github.com/clarkezone/simple_c_compiler then on to stage two
