### ISSUE TITLE
Broken Link in Stage 4 footnotes

### ISSUE THREAD

**Issue by chadbramwell** [nlsandler/write_a_c_compiler#10]
https://norasandler.com/2017/12/28/Write-a-Compiler-4.html#fn1 links to http://web.cse.ohio-state.edu/~babic.1/COperatorPrecedenceTable.pdf which no longer exists.

Perhaps https://en.cppreference.com/w/c/language/operator_precedence would be a better link?

**Comment by nlsandler** [comment]
Thanks for catching this! I've updated the footnote to include the link you suggested.
