### ISSUE TITLE
Stage 4, invalid/split_le.c cannot be lexed

### ISSUE THREAD

**Issue by stevejb71** [nlsandler/write_a_c_compiler#2]
There's no token for = at stage 4, so invalid/split_le.c cannot pass the lexer (but the blog says all invalid files should).

split_le.c is:
```
int main() {     return 1 < = 2; }
```

**Comment by nlsandler** [comment]
Thanks for filing this! I've deleted split_le.c

**Comment by stevejb71** [comment]
Welcome. By the way, the compiler blog is excellent.
