### ISSUE TITLE
Writing a C Compiler

### ISSUE THREAD

**Issue by ijean** [nlsandler/write_a_c_compiler#23]
Hi Nora,
just bought the early access "Writing a C Compiler" from No Starch Press. I wanted to ask about the code/scripts mentioned in the book, where can one find this code ?
Thanks,
Jean

**Comment by nlsandler** [comment]
Hi Jean,

Thanks for purchasing the book! The code will be available on Github once the book is released.

Best,
Nora

**Comment by ijean** [comment]
Thanks, looking forward to read all the chapters.
