### ISSUE TITLE
Trees on week 3 are really small when viewed using Firefox

### ISSUE THREAD

**Issue by retop56** [nlsandler/write_a_c_compiler#27]
Attached screenshots below

The trees in the attached screenshot are incredibly small when viewed using Mozilla Firefox, but appear to be normal when viewed using Google Chrome. Changing the `height: auto;` declaration in the `.post-content img` CSS selector to `height: 15em;` seems to resolve the issue for me on Firefox, while still maintaining a normal view on Chrome (I checked). 

![trees_for_ants](https://github.com/nlsandler/write_a_c_compiler/assets/13913368/de9cf4da-7818-46f2-9a3a-68757d851380) 
![trees_for_humans](https://github.com/nlsandler/write_a_c_compiler/assets/13913368/944670da-a5d8-4ca2-9b30-48c1d2d5d9d5)

**Comment by nlsandler** [comment]
Thanks for flagging this - I also see this issue in Firefox.

**Comment by nlsandler** [comment]
Took me a while to get around to this, but I've finally fixed it (by setting `flex` property directly on the divs containing these images). Thanks again for reporting it!
