### ISSUE TITLE
AST changes on Week 5 are not all bolded

### ISSUE THREAD

**Issue by retop56** [nlsandler/write_a_c_compiler#28]
The AST addition "Assign(string, exp)" on week 5 is not bolded. First image shows the AST definition on week 4, and second image shows the unbolded addition of the Assign AST on week 5.
![Screenshot 2024-01-24 005243](https://github.com/nlsandler/write_a_c_compiler/assets/13913368/eacb9f9a-feb4-44b0-b91f-e5e70f6d6975)
![Screenshot 2024-01-24 005142](https://github.com/nlsandler/write_a_c_compiler/assets/13913368/e914d80e-ed53-40ce-ad5b-20fa54bc07dd)

**Comment by nlsandler** [comment]
Thanks for reporting this! Just fixed it - the `Assign` constructor is now bolded in this listing.
