### ISSUE TITLE
Some stage 4 files cannot be lexed (at stage 4 of the blog)

### ISSUE THREAD

**Issue by stevejb71** [nlsandler/write_a_c_compiler#9]
Files starting with skip_on_failure_ can't be lexed at stage 4.

The blog says "It should work for all stage 1-4 examples in the test suite, including the invalid ones."

**Comment by chadbramwell** [comment]
I had this same issue! Looks like they depend on local variables which is a stage 5 thing.

**Comment by nlsandler** [comment]
Thanks for flagging this! I've updated the blog to clarify that you don't need to handle lexing and parsing those three test cases at this stage.
